site_name: EVCache
pages:
    - Home: index.md
    - Introduction: introduction.md
    - Features: features.md
    - Using EVCache Clent: using.md
    - Configuration : config.md

theme: cinder

extra_css:
    - css/extra.css